### ISSUE TITLE
API returning weird results

### ISSUE THREAD

**Issue by SiriosDev** [Pirate-Weather/pirateweather#229] opened 2024-05-18 13:13 UTC
### Describe the issue

# Strange data are appearing in the forecast
## here some examples: 
![image](https://github.com/Pirate-Weather/pirateweather/assets/26876994/caa3c18c-7c61-4520-a44b-a27d5c664871)
https://merrysky.net/forecast/Europe/ca
![image](https://github.com/Pirate-Weather/pirateweather/assets/26876994/91729225-694e-482f-945e-d44ebb2079b0)
https://merrysky.net/forecast/Italy/ca
![image](https://github.com/Pirate-Weather/pirateweather/assets/26876994/8bc5837d-7bdc-41ec-a08f-de8da93ce07e)
https://merrysky.net/forecast/Rome/ca

## Same in HA so is probably api side problem
![image](https://github.com/Pirate-Weather/pirateweather/assets/26876994/bba9b384-790b-46e4-a264-2b3b95da2994)
![image](https://github.com/Pirate-Weather/pirateweather/assets/26876994/7e5de31f-de3c-4e86-9079-bfa89d614cd4)

### Acknowledgements

- [X] I have searched this repository to see if the issue has already been reported.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment] 2024-05-18 16:11
I've queried the API in my browser and am seeing the same issue for the locations you have specified. If I exclude HRRR and NBM models for my location I'm seeing the same issue.

I checked out [SpotWx](https://spotwx.com/) for Rome, IT and the data appears to be normal:
![image](https://github.com/Pirate-Weather/pirateweather/assets/10248058/d36026c1-6491-4ed6-9608-3d96d1d7540c)

So whatever the issue is likely on PW's end and may not happen when the 12Z run gets integrated into the API. I'll ping @alexander0042 to see if he can look into this though it is a holiday this weekend so he may not look at it until next week.

**Comment by cloneofghosts** [comment] 2024-05-18 18:09
The 12Z GFS run has been integrated into the API and the temperature glitches are gone. While the temperature issues have been fixed I'm going to keep this one open so the underlining issue can be fixed.

**Comment by alexander0042** [comment] 2024-06-05 14:17
Holy cow! Don't know how I missed this one, but that's really not good! I'll go back and look at the model data for that time step (I'm still archiving everything) to see if I can tell what's going on. 

Separately, I'll add a to-do to just make some sort of sanity check here. The API should never return those kinds of numbers, and would be better to error out rather than return that.

**Comment by rnorth** [comment] 2024-06-14 07:01
Not quite the same scale, but I'm also seeing some forecast temperatures of absolute zero on merrysky, so there must be something else not right:

<img width="913" alt="image" src="https://github.com/Pirate-Weather/pirateweather/assets/132175/9c79aa19-826d-43a1-ae27-f523e4fda320">

<img width="503" alt="image" src="https://github.com/Pirate-Weather/pirateweather/assets/132175/45bf7c6f-8e9d-4f3e-8148-77df635e6ede">

**Comment by cloneofghosts** [comment] 2024-06-14 14:45
I queried your location in my browser and I'm seeing the same issues that Merry Sky is showing. I also see that a bunch of the data points are also returning weird results. It doesn't seem to be just strictly the GFS model as I'm also seeing similar issues for my location which uses NBM as the primary model.

Will ping @alexander0042 to look into this issue.

**Comment by cloneofghosts** [comment] 2024-06-14 18:32
@alexander0042 I'm assuming you're still working on this? I've seen times where it's been fixed and other times when it isn't.

**Comment by rnorth** [comment] 2024-06-15 10:26
Thank you @cloneofghosts - I really appreciate your extra investigation. For what it's worth, today the forecasts in Merry Sky for my exact location appear just fine for all of the next 7 days. So evidently this is an intermittent issue 🙈!

**Comment by cloneofghosts** [comment] 2024-06-15 15:45
Yeah, the issue seems to come and go. Will try pinging @alexander0042 to see if he can look into this but it may not be fixed until Monday.

This issue is affecting all locations though locations with multiple models are affected less. For my location the UV Index is majority messed up and days 7&8 have some messed up data points.

**Comment by SiriosDev** [comment] 2024-06-16 17:18
New info now uv too go wrong (not everytime) in fact on merry all seems correct, but thanks to HA stats i've seen this peak of almost `+900.000.000.000.000.000` and `-300.000.000.000.000.000`
![image](https://github.com/Pirate-Weather/pirateweather/assets/26876994/3dd4d07c-f56b-4d3e-ac5d-a34ef5cabdcd)

**Comment by alexander0042** [comment] 2024-06-17 13:53
Thanks for responding to this @cloneofghosts, and really sorry for all the instabilities here. One of the two instances that runs the backend seems to have run out of space (which should never happen), which meant that it was having trouble writing new results in. This is why so many crazy results started popping up. Short and long term fixes:

1. Reboot the instance. The other instance is more than large enough to handle the load and isn't showing this issue.
2. I'm adding some logic to my load balancer this morning to check for errors in the response and stop routing requests to that instance if that happens. 
3. I'm going to look into how to automatically reboot an instance that starts throwing too many errors
4. Very long term, I want a better way to storing and updating data from the ingest pipeline to the servers. Currently, it just overwrites the zarr files on disk, which works, but can be prone to these sorts of instabilities. LMDB seems promising for this, but I kept running into file locking issues, and while Redis worked great, storing everything in memory isn't really feasible for this size of project. Thinking about [RocksDB](https://en.wikipedia.org/wiki/RocksDB), but I'd have to write a zarr backend for it

**Comment by cloneofghosts** [comment] 2024-06-17 14:11
Ah the internal server error I had encountered earlier was from you rebooting the instances. Everything seems to be fine this morning but will keep an eye out for any crazy results.

I also noticed that the GFS model hasn't been integrated since yesterday's 18Z run. `"gfs": "2024-06-16 18Z",` Not sure if it's related to the reboot and will sort itself out or is a separate issue.

**Comment by alexander0042** [comment] 2024-06-17 14:42
Yea, related to the same issue. One of the instances failed in a much more graceful way with that ingest, which was the goal. Both should sync over to the 6Z run shortly

**Comment by jepminer** [comment] 2024-06-18 09:18
Just to weigh in I've seen the absolute 0 thing a couple times now and I'm also currently looking at a rain graph that says 49mm on Thursday which I'm not sure is possible? This is for Ashford kent, uk

**Comment by cloneofghosts** [comment] 2024-06-18 15:04
@alexander0042 Seems like the GFS model got stuck again. Sometimes I see yesterdays 06Z run and sometimes I get yesterdays 18Z run.

> ![Screenshot_20240618_101707_Home Assistant](https://private-user-images.githubusercontent.com/33632057/340618843-aaded74b-17d3-4209-8fc9-f551596c69bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MjI3OTIsIm5iZiI6MTcxODcyMjQ5MiwicGF0aCI6Ii8zMzYzMjA1Ny8zNDA2MTg4NDMtYWFkZWQ3NGItMTdkMy00MjA5LThmYzktZjU1MTU5NmM2OWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE0NTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZDQwNTFmMzFhOTFhN2RjNWMxNWU5MTU3NzZiYzg4NTUwMzNiYTgzMjFkZjljOTljZmVlMzRkYmVmOTcwZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cJ6NjZdX16EETkOBcJYeJImBOYqthHUWDpNiL5zcmgY) Just to weigh in I've seen the absolute 0 thing a couple times now and I'm also currently looking at a rain graph that says 49mm on Friday which I'm not sure is possible? This is for Ashford kent, uk

I queried your location in the browser and I see 5mm of rain in the forecast. Does your HA card still show 49mm still or has it changed?

**Comment by jepminer** [comment] 2024-06-18 16:18
> @alexander0042 Seems like the GFS model got stuck again. Sometimes I see yesterdays 06Z run and sometimes I get yesterdays 18Z run.
> 
> > Just to weigh in I've seen the absolute 0 thing a couple times now and I'm also currently looking at a rain graph that says 49mm on Friday which I'm not sure is possible? This is for Ashford kent, uk
> 
> I queried your location in the browser and I see 5mm of rain in the forecast. Does your HA card still show 49mm still or has it changed?

Still says 49mm

**Comment by alexander0042** [comment] 2024-06-18 17:43
Ok, I can confirm at least that I'm getting ~4.9 cm for daily rain accumulation in that location, which does seem to be an order of magnitude higher than it should be! Investigating now

**Comment by cloneofghosts** [comment] 2024-06-18 18:48
Hm, I must be querying the wrong location then as I see this `"precipAccumulation": 0.519,` for Friday which is what I posted earlier. I wonder if it's related to the GFS model not updating as I posted above.

**Comment by jepminer** [comment] 2024-06-18 19:09
> Ok, I can confirm at least that I'm getting ~4.9 cm for daily rain accumulation in that location, which does seem to be an order of magnitude higher than it should be! Investigating now

Now it's updated to say 14mm

**Comment by alexander0042** [comment] 2024-06-18 19:10
In the 45 minutes between our two comments I fixed it (sort of). @cloneofghosts's hunch was correct, it was related to the GFS data not being ingested. This didn't make sense initially, since GFS isn't used for accumulation as a general rule... however, there was a really straightforward bug that meant GFS data was being used for accumulation instead of GEFS, and that's being addressed in the currently rolling out 2.10!

The ingest issue is still outstanding, and it is a strange one. I think it's related to the rate at which updates are happening, and so I've tried adjusting that timer, so we'll see if that fixes it

**Comment by cloneofghosts** [comment] 2024-06-18 19:27
@alexander0042 I can make a new issue for this but it looks like NBM has stopped integrating again. The last run being yesterdays 21Z run. `"nbm": "2024-06-17 21Z",`

Other than that issue has the main issue been solved and we can close this?

**Comment by alexander0042** [comment] 2024-06-18 19:35
Yea, both of them glitched, but should be synced back up in the next 20 minutes or so! At the moment you'll get a mix of results depending on which server you get routed to, since one has the updated data and one doesn't

**Comment by cloneofghosts** [comment] 2024-06-18 19:39
Alright, cool. I will close this for now but if any weird results come up again feel free to either open a new issue or reply to this one.

**Comment by cloneofghosts** [comment] 2024-06-23 22:15
The negative temperature issue seems to have popped up again today. Screenshot of the daily data is from Breezy Weather

![Screenshot_20240623_181102_Breezy Weather](https://github.com/Pirate-Weather/pirateweather/assets/10248058/25671d1e-f379-41a5-a22c-b25ba95e7ea4)

**Comment by alexander0042** [comment] 2024-06-24 13:54
Shoot. was hoping this was fixed, but apparently not! Did it self-correct, or are you still seeing this datapoint?

**Comment by jepminer** [comment] 2024-06-24 13:56
> Shoot. was hoping this was fixed, but apparently not! Did it self-correct, or are you still seeing this datapoint?

Still seeing it here

**Comment by cloneofghosts** [comment] 2024-06-24 14:09
> Shoot. was hoping this was fixed, but apparently not! Did it self-correct, or are you still seeing this datapoint?

I'm still occasionally seeing this issue and sometimes current visibility is -999. `"visibility": -999,` Taking a look at the sourceTimes section I see that NBM and GFS have gotten stuck again with the last update being 3/4 days ago:

```
"sourceTimes": {
    "hrrr_subh": "2024-06-24 12Z",
    "hrrr_0-18": "2024-06-24 11Z",
    "nbm": "2024-06-21 00Z",
    "nbm_fire": "2024-06-24 06Z",
    "hrrr_18-48": "2024-06-24 06Z",
    "gfs": "2024-06-20 12Z",
    "gefs": "2024-06-24 06Z"
},
```

**Comment by alexander0042** [comment] 2024-06-24 14:11
Ok, that's really helpful, and again, so sorry for the problems! I just set a restart policy for my back-end servers, which should fix this in the medium term! Rolling out now, so data should be resolved in 20 minutes or so. 

In the next two weeks, I'll move things from disk based storage to a Redis like database called [Garnet](https://github.com/microsoft/garnet). In my testing it's been faster than disk, rock solid, and beautifully handles lots of overwriting keys, which is what I need it to do. It should also make ingest faster, which is always good!

**Comment by cloneofghosts** [comment] 2024-06-24 15:53
Things seem to be sorted so I'm going to close this issue. If it pops up again feel free to reply to this issue or create a new one.

**Closed by cloneofghosts** 2024-06-24 15:53 UTC
Labels: bug, priority: high

**Comment by SiriosDev** [comment] 2024-08-17 16:55
![image](https://github.com/user-attachments/assets/2672623a-4b80-4173-92b0-0f6c18816f8b)
oh no it's back🥲

**Comment by cloneofghosts** [comment] 2024-08-17 18:53
> ![image](https://private-user-images.githubusercontent.com/26876994/358858452-2672623a-4b80-4173-92b0-0f6c18816f8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MjA4NzUsIm5iZiI6MTcyMzkyMDU3NSwicGF0aCI6Ii8yNjg3Njk5NC8zNTg4NTg0NTItMjY3MjYyM2EtNGI4MC00MTczLTkyYjAtMGY2YzE4ODE2ZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE4NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjdiNDM2MWZkZDUwYzc1MTJlOTYxYjc2YTdjYzkxZmRhODYyZmEwZjg0ODI4YjUzNjBkN2ZkNzA5NWJmMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KKQ2SUZ09B9SQgMwTfd9_z66CdqbzMwUzf2euniMTA8) oh no it's back🥲

Yeah `windSpeed` is a bit bugged at the moment see #294. It could be that the latest GFS run integrated into the API has issues or its possibly related to V2.1 API update see: #293

**Comment by fenty17** [comment] 2024-08-17 18:59
I have a new related issue but with wind speed of extreme values. Shetland Islands, UK. It gets windy here, but not this windy! [Issue 294](https://github.com/Pirate-Weather/pirateweather/issues/294)
