### ISSUE TITLE
exclude=hourly,minutely does not longer work for me

### ISSUE THREAD

**Issue by GetAway1** [Pirate-Weather/pirateweather#202] opened 2024-04-28 13:12 UTC
### Describe the bug

https://api.pirateweather.net/forecast/xxx/51.16%2C6.93?lang=de&exclude=hourly,minutely&units=ca

xxx for the api-key

### Expected behavior

example is not possible now

### API Endpoint

Production

### Location

"latitude": 51.16,"longitude": 6.93,

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment] 2024-04-28 14:38
Duplicate of #108

**Closed by cloneofghosts** 2024-04-28 14:38 UTC
Labels: bug, duplicate
