### ISSUE TITLE
Temperature min/max vs low/high

### ISSUE THREAD

**Issue by trevorturk** [Pirate-Weather/pirateweather#5] opened 2022-05-25 21:15 UTC
Hello! 👋 I'm just familiarizing myself with your project and I noticed in your docs:

> Dark Sky provides both temperatureHigh and temperatureMax values, and since I am not sure what the difference between them is, the same value is currently used for both.

Indeed, this is confusing! The best (only?) explanation I've seen is here: https://status.darksky.net/2017/08/29/daily-updates.html -- I'll quote it here in case they take down their blog:

> A longstanding complaint with the Dark Sky API is that we report daily temperatures differently than other services: we report the minimum and maximum temperature during a given date, while other services report the daytime high and overnight low. (Put another way, our service reports temperature extrema between midnight and midnight, while other services report extrema from dawn to dawn.) These two were typically the same for daily high temperatures, but typically off by one day for the daily low temperatures (which usually occur around dawn). To address this complaint, we have added two new fields to daily data points: temperatureHigh and temperatureLow, which match the calculation methods used by other weather services. (temperatureMin and temperatureMax are still supported, but are now considered deprecated.)

Interestingly, the official Dark Sky iOS app seems to use the (allegedly deprecated) min/max instead of the new high/low. 

Their documentation also aims to explain the differences between the data points (a bit too succinctly for my taste) but it makes sense once you have the context from their blog post. I'll quote it here as well:

> temperatureHigh: The daytime high temperature.
> temperatureLow: The overnight low temperature.
> temperatureMax: The maximum temperature during a given date.
> temperatureMin: The minimum temperature during a given date.

To add some additional color, note that the AerisWeather API has a /forecast endpoint with "filters" which I found interesting in comparison: https://www.aerisweather.com/support/docs/api/reference/endpoints/forecasts/#filters -- so, I believe the including the mdnt2mdnt filter and then taking the minTemp/maxTemp would approximate the behavior of Dark Sky's min/max, for example. 

As an aside, for a bit of background, this a point of contention with the more sophisticated users of my iOS weather app (https://helloweather.com) because the sources are inconsistent about when/what the overnight low temp is, and I really haven't found a great solution where all of the data sources we support are fully consistent. Instead, I tend to default to making our iOS app "look like" the data source's native iOS app. (Thus me noticing that Dark Sky's official app continues to use min/max even though they say it should be considered deprecated.)

Anyway, I'm not sure how this might impact your model (perhaps you'll choose to only support one or the other) but I figured I'd drop you a note since this confused me as well. Feel free to close this issue in any case, I wasn't quite sure where to post this info!

**Comment by trevorturk** [comment] 2022-05-26 17:05
That's great, thank you! I'm glad you like the Hello Weather app. It's been a side project for a few years and I've learned more about weather data than I intended when I initially set out... I'm sure you know the feeling!

I'm sorry I forgot to mention the 4am thing. It's funny, because in at least with AerisWeather they claim 7am is the "industry standard" (see the link I posted above) and IIRC one other source said something similar. In any case, for Pirate Weather it makes sense to match Dark Sky, of course. 

I'm trying to implement Pirate Weather in Hello Weather now, using a new backend system I've been building that makes it easier to support multiple sources. (I hope to extract this into a product for general use -- I'll write you separately about that once I get a little further along on the tech side.) So, I have a pretty good test bed for comparing sources and ensuring we have equivalent data etc. The only other thing I noticed is that I believe you're returning times in UTC? I'm not 100% sure I have that right, but I'll be investigating more. If that's the case, I think that's worth changing. All of the other sources I use (and including Dark Sky) return epoch timestamps or datetime strings in the local timezone from what I can tell, so that stood out to me as a compatibility issue. 

Oh, and I noticed your "units" param is "uk" as opposed to "uk2" in Dark Sky. Obviously not a big deal, but I figured I'm mention anything that I noticed as I started hooking into your API.

Thanks!

**Comment by alexander0042** [comment] 2022-05-27 15:06
I'd love to see Pirate Weather added in there, so definitely let me know how it goes! 

For the times (I should clarify the docs here) everything is always returned in UTC. The local time zone is used to calculate the daily results, so I have that incorporated, but Dark Sky returned UTC, and I find it much easier to work with. The Dark Sky docs are a little confusing here: 

> time
> The UNIX time at which this data point begins. minutely data point are always aligned to the top of the minute, hourly data point objects to the top of the hour, daily data point objects to midnight of the day, and currently data point object to the point of time provided all according to the local time zone.

Which makes it seem like it'd be in local, but they mean that the response is the UTC time for midnight local. As a sanity check, I double checked this today and it lines up (for the record, it's raining here, so the win goes to PW):
![image](https://user-images.githubusercontent.com/26213938/170726305-299a7955-669d-49e3-9875-f4c35a60c0b2.png)
![image](https://user-images.githubusercontent.com/26213938/170726360-ca9db99b-be59-42cc-bd2d-eb631ff8c92d.png)

A lot of packages automatically adjust for this though, so whatever you're using might convert it to local anyway.

Also, while `uk2` is the official unit version, I'm just using the first two characters to select the system, so either will give you the same results (as would uk9). I might need to change this at some point, but until there's a need for a `uk3`, this works well enough. I am curious what the originak `uk` was though...

**Comment by trevorturk** [comment] 2022-05-27 21:12
Ok, I think the problem may be the timezone library you're using. I'm comparing a request to DS and PW:

https://api.darksky.net/forecast/API_KEY/41.87,-87.62 -> "timezone": "America/Chicago"
https://api.pirateweather.net/forecast/API_KEY/41.87,-87.62 -> "timezone": "America/Detroit"

This location is meant to be "the middle of Chicago" so it should have "America/Chicago" as the timezone: https://goo.gl/maps/TpymXu7CQQ75U2gP6

The epoch timestamps make sense if you take that into consideration, but this probably need to be fixed on your end or the data will come out strangely, if you're not picking the correct timezone for the 4am start etc?

**Comment by alexander0042** [comment] 2022-05-27 22:04
Ok, that explains it then! 

That's actually a question I've been puzzling over for some time now. The issue is that looking up the exact time zone adds a little bit of time to requests, and for most applications it doesn't really matte, since the results are returned in UTC anyway, and at most it should be off by an hour. However, you're right that it's better for it to be correct, and I'm not convinced it was having as much of an impact as I thought it was, especially for warm starts of the Lambda instance. 

If you want to try this yourself, there's another URL parameter that forces it to use the exact time zone location: `tz=precise`. This should solve any issues you're having on that front while I keep trying to optimize the response time in other ways.

**Comment by trevorturk** [comment] 2022-05-27 22:09
Ok! Yeah, that seems to solve the issue for me. I'm not sure what to suggest on your end -- timezone lookup stuff is annoying. I was using https://github.com/zverok/wheretz but I think the data was becoming stale, but it seems to have been updated somewhat recently now. I'm using https://www.geonames.org now for some cases (with plenty of caching) -- that's one thing to consider is once you do a lookup, you can likely cache it for a while, eh?

**Comment by alexander0042** [comment] 2022-05-27 22:15
So annoying, and I've learned that the trick with this API is to optimize response times as much as possible- both because it's always better to return data faster, but also because when executions are in AWS Lambda, each millisecond shaved off saves some of the operational costs. Doesn't seem like much, but it adds up when it's multiplied by a million calls per week. 

I'm using [timezonefinder](https://github.com/jannikmi/timezonefinder) at the moment, and broadly speaking it works really well. it's up to date, entirely offline, and comfortably fits in the instance layer, so just a question of 0.1 seconds here or there,

**Comment by trevorturk** [comment] 2022-05-31 17:20
Howdy! Sorry to pile onto this issue, and feel free to ignore this one, but I noticed another small deviation from the DS API. For `precipType` PW sometimes returns `none` where DS seems to only use `rain` and `snow` in my experience, and seems to default to `rain` instead of returning `nil`.

Their docs for reference:

```
precipType optional
The type of precipitation occurring at the given time. If defined, this property will have one of the following values: "rain", "snow", or "sleet" (which refers to each of freezing rain, ice pellets, and “wintery mix”). (If precipIntensity is zero, then this property will not be defined. Additionally, due to the lack of data in our sources, historical precipType information is usually estimated, rather than observed.)
```

Perhaps PW could return `rain`, `snow`, or `nil` instead of `none`? I can handle this easily, so nbd, but I wanted to point it out since I noticed it!

**Comment by alexander0042** [comment] 2022-06-01 13:26
This one has been on my radar, and so I'm happy I'm kind of dubious about just skipping over fields, since it doesn't feel like a great solution; however, you are right that it's technically the way they do it. I really like the nil approach though, since looking at it again, that's much closer to their implementation. 

One thing I'll preempt you on also relates to precipitation, and it's a much larger problem. Dark Sky defines precipitation accumulation only for snow, and always uses cm as the unit. I didn't realize this when I originally set things up, and it still seems unusual to ignore it for rain. 

Clients sometimes implement around this by summing up hourly precipitations to get accumulation, but it feels like a clunky way to do it (for example, [the home assistant integration](https://github.com/alexander0042/pirate-weather-ha/blob/e95083f235817ba3f5653114afe5602ab323b8ae/custom_components/pirateweather/weather.py#L185), or [this issue](https://github.com/alexander0042/pirate-weather-ha/issues/30#issuecomment-1040776225)). 

My current game plan here is to go with the Dark Sky implementation for compatibility, but add in a `rainaccumulation` field that provides the rain accumulation, leaving `precipAccumulation` for snow. This technically would break both DS compatibility and existing behavior, so I'll give a lot of heads up before implementing it, but I suspect it'll break fewer things by adding an extra field compared to the way `precipAccumulation` works now.

**Comment by trevorturk** [comment] 2022-06-01 15:21
💯 these are some of the more confusing aspects of their API for sure. I have some old emails and GitHub issues I'll share for supporting documentation, but I thought daily `precipAccumulation` should only be used for snow, and I think it does (or at least it's supposed to) switch between in/cm. Also, the moon phase stuff is wacky, I'll share some details for that, too. I like your approach, though, and thank you for the links. Here's what I have currently, but I'd love to get to the bottom of things to ensure full compatibility:

Possible `precipType` values question: [Gmail - precipType possible values?.pdf](https://github.com/alexander0042/pirateweather/files/8815321/Gmail.-.precipType.possible.values.pdf)

I never heard back (I think they already sold to Apple at this point) but I believe I've only ever seen `rain` and `snow`. 

Rail accumulation question: [Gmail - Rain accumulation:amount?.pdf](https://github.com/alexander0042/pirateweather/files/8815329/Gmail.-.Rain.accumulation.amount.pdf)

Dark Sky docs:

> precipAccumulation optional, only on hourly,currently and daily
> The amount of snowfall accumulation expected to occur (over the hour or day, respectively), in inches. (If no snowfall is expected, this property will not be defined.)
> precipIntensity optional
> The intensity (in inches of liquid water per hour) of precipitation occurring at the given time. This value is conditional on probability (that is, assuming any precipitation occurs at all).
> SI units are as follows:
> precipIntensity: Millimeters per hour.
> precipAccumulation: Centimeters.

So, in my app, I've been processing it like this:

* hourly.precipIntensity = amount of rain for the hour (us: in/hr, else mm/hr)
* daily.precipIntensity * 24 (hours) = amount rain for the day (us: in/hr, else mm/hr, multiple by 24hrs in the day)
* hourly.precipAccumulation = snow accumulation for the hour (us: in/hr, else cm/hr)
* daily.precipAccumulation = snow accumulation for the day (us: in/day, else cm/day)

I think that's all correct, but I'd love to get your take on things. Perhaps you talked to the Dark Sky folks about `precipAccumulation` always being cm -- that would be a major gotcha since their docs say it's in for us units -- or maybe you've just been able to determine how they're doing things by looking at the data? Issue #30 seems like you've paid close attention, so I'd welcome your advice. 

FWIW the `moonPhase` is also strange, it seems to me like they're using the suncalc library, per: https://github.com/mourner/suncalc/issues/14 which isn't terribly precise, but (again) striving for compatibility for now...

From the DS docs:

> moonPhase optional, only on daily
> The fractional part of the [lunation number](https://en.wikipedia.org/wiki/Lunation_Number) during the given day: a value of 0 corresponds to a new moon, 0.25 to a first quarter moon, 0.5 to a full moon, and 0.75 to a last quarter moon. (The ranges in between these represent waxing crescent, waxing gibbous, waning gibbous, and waning crescent moons, respectively.)

So, for help converting this into a string for display to customers, I emailed them:  [Gmail - Moon Phase question.pdf](https://github.com/alexander0042/pirateweather/files/8815448/Gmail.-.Moon.Phase.question.pdf) -- there's a calculation in there that's somewhat different from what the Tomorrow.io docs suggest here: https://docs.tomorrow.io/reference/data-layers-core:

> 0: New (0.0625-0.9375)
> 1: Waxing Crescent (0.0625-0.1875)
> 2: First Quarter (0.1875-0.3125)
> 3: Waxing Gibbous (0.3125-0.4375)
> 4: Full (0.4375-0.5625)
> 5: Waning Gibbous (0.5625-0.6875)
> 6: Third Quarter (0.6875-0.8125)
> 7: Waning Crescent (0.8125-0.9375)

...which is somewhat far off the Dark Sky calculations, but I haven't been able to find an authoritative formula to use. 

Also in my testing, it seems like Dark Sky may be using the "end of the day" local timestamp to calculate the moon phase. So, I'm using a Ruby port: https://github.com/fishbrain/sun_calc and pulling out the phase like so: `SunCalc.moon_illumination(daily.time.end_of_day).dig(:phase)`. I'm not feeling terribly confident about this, but trying to maintain compatibility for now...

**Comment by trevorturk** [comment] 2022-06-01 21:38
Minor update -- I was digging through my old VCR cassettes (https://github.com/vcr/vcr) and found a Dark Sky response with `precipType` set to `sleet` -- apologies for missing that earlier.

**Comment by rosenbergj** [comment] 2023-01-11 21:08
Hi! I just learned about this project in my search for a weather API to replace Dark Sky.

Perhaps unusually, I do rely on all 4 (well, 3 of the 4) of the temperature extrema data points in my application. My goal is to display the *next* high or low temperature, switching from a display of the high to a display of the low when the high is reached, and vice versa. (In the circumstance when the temperature is rising all evening and night, relatively uncommon but possible in the US mid-Atlantic, I want to print "n/a" between 6pm and midnight, switching to the next day's high at midnight. And vice versa for "temperature falling all day" and "between 6am and noon".) To do this, I also rely on the timestamps provided in Dark Sky for each of these, such as `temperatureMinTime`.

The notes I have for how to do this with Dark Sky are:

```
# Darksky logic:
#   Today's date is the right day to look at for next high/low, in all circumstances
#   Midnight to 6am, temperatureMin is a good low if in the future; else show high
#   6am to 6pm, temperatureHigh is a good high if in the future; else n/a in morning, show low in afternoon
#   6pm to midnight, temperatureLow is a good low if in the future, else n/a
```

I don't know if it's possible to do this in Pirate Weather (I am in the process of getting an API key), but it would be great if I can! None of the other APIs I've found handle this correctly in all of the various edge cases that my climate provides. I found this issue and wanted to provide more information to support the need for the distinct data points.

Thank you!

**Comment by rosenbergj** [comment] 2023-01-13 15:20
Thank you, much appreciated!! Here are two examples that cover many of the edge cases I've found:

Example 1:
* Day 0: Temperatures max out at 50° at 4pm, dropping to 40° by midnight
* Day 1: Temperatures start at 40°, dropping to 30° by 4am, then rising to 35° at 4pm, then dropping to 25° by midnight
* Day 2: Temperatures start at 25°, and continue dropping to 20° at 4am

Example 1 desired behavior:
* On day 0, 11:45pm: That day's `temperatureLow` is 30°, with a time stamp of about 4.25 hours in the future (i.e. the timestamp falls on day 1). The `TemperatureMin` is in the past.
* On day 1, 12:15am: That day's `TemperatureMin` is 30°, with a time stamp of about 3.75 hours in the future. I believe the `TemperatureLow` should be 20° with a timestamp of over 24 hours in the future, but I'm not sure of that.

Example 2: (this was real weather in the US mid-atlantic this week! It is 10am on "day 1" as I'm writing this)
* Day 0: Temperatures rise all day, from 35° at 12:01am until 56° at 11:59pm.
* Day 1: Temperatures continue to rise, reaching a high of 58° at 4am. Then temperatures begin to fall and continue to fall all day, reaching 35° at 11:59pm
* Day 2: Temperatures reach 32° at 7am and then begin to rise again

Example 2 desired behavior:
* On day 0, 7pm: That day's `temperatureLow` is in the past. I don't know the exact timestamp or value, but presumably sometime between midnight and 7am on day 0.
* On day 1, 12:15am: That day's `temperatureMin` is timestamped at 12:01am, in the past. `temperatureHigh` is 58° at 4am.
* On day 1, 6am: Same as 12:15am. `temperatureHigh` is now in the past.
* On day 1, 6pm: Ideally `temperatureLow` is at 7am the next day, rather than some earlier arbitrary cutoff like 6am, though I'm not 100% sure this is Dark Sky behavior

Thank you again!!

**Comment by cloneofghosts** [comment] 2023-01-22 20:21
I know that DarkSky isn't very transparent on this but other APIs and websites that I've usually use 6am-6am as the period for high/low temp and if they offer min/max they use 12am-12am.

Since the overnight lows typically occur around 6am I think having high/low be from 6am-6am and having min/max being from 12am-12am makes the most sense in this situation.

**Comment by alexander0042** [comment] 2023-01-24 18:45
OK, now that I got alerts working I flipped back to this! This was a combination of bug + logic issue, but I just released v1.3 which addresses both. I'm updating the docs now, but this is the setup:

```
    temperatureHigh: The daytime high temperature (6:00 am to 6:00 pm).
    temperatureLow: The overnight low temperature (6:00 pm to 6:00 am on the next day).
    temperatureMax: The maximum temperature during a given date (12:00 to 12:00).
    temperatureMin: The minimum temperature during a given date (12:00 to 12:00).
```
As far as I can tell, this aligns with how Dark Sky did it, which is always the goal. I'm still using 4:00 to 4:00 as the period for the icon and text summary, but otherwise everything is on the expected 12:00 to 12:00 frame. 

Let me know if this matches the expected behavior on your end or if I need any additional tweaking here.

**Comment by rosenbergj** [comment] 2023-01-24 19:11
Thank you for working on this so quickly! Right now I'm seeing these differences at location (39.95,-75.17):

Dark Sky:
* temperatureHighTime: 2:17pm (several minutes from now)
* temperatureLowTime: 3:29am tomorrow (in about 13 hours)
* temperatureMaxTime: same as temperatureHighTime
* temperatureMinTime: 5:46am today (**about 8 hours ago**)

Pirate Weather:
* temperatureHighTime: 2:00pm (several minutes ago)
* temperatureLowTime: 4:00am tomorrow (in about 14 hours)
* temperatureMaxTime: same as temperatureHighTime
* temperatureMinTime: 10pm today (**in about 8 hours**)

This particular time doesn't have a practical impact on my project (I only look at temperatureMin between midnight and 6am), but it's a material difference that I wanted to point out. Does Pirate Weather ever report high/low/min/max in the past? If not, then it will indeed continue to have occasional big differences from Dark Sky in these values.

**Comment by alexander0042** [comment] 2023-01-24 19:28
Thanks for testing this so quickly- you checked it out before I even had a chance to update the docs!

Your assumption here is correct, PW will always return the forward looking values, which is a difference from how Dark Sky did it. Unfortunately, this is a vary hard to fix issue with the setup. Since everything is file based, the API doesn't know anything about what happened in the past, so can only return values looking forward, and I would have to add a bunch of file system reads in order to address it.

The one way around this is to use the short-term time-machine functionality to request the forecast as it was at midnight. This means you wouldn't get the most up to date data, but since it's reading previous files, everything would be calculated for the entire day. So something like: `https://api.pirateweather.net/forecast/<API_KEY>/39.95,-75.17,1674536400` would give you the forecast from today at 12:00 am, ensuring that all the times are in the futire

**Comment by cloneofghosts** [comment] 2023-01-25 23:23
@alexander0042 There's a bug with the new high/low setup for the current day after 6pm where it's using the highest forecasted temperature and not one for the current day.

```
        "time": 1674622800,
        "icon": "snow",
        "summary": "Snow",
        "sunriseTime": 1674649875,
        "sunsetTime": 1674683974,
        "moonPhase": 0.14013338096939384,
        "precipIntensity": 0.927,
        "precipIntensityMax": 1.1494,
        "precipIntensityMaxTime": 1674702000,
        "precipProbability": 1.0,
        "precipAccumulation": 4.6349,
        "precipType": "snow",
        "temperatureHigh": 0.29,
        "temperatureHighTime": 1674900000,
        "temperatureLow": -9.96,
        "temperatureLowTime": 1674694800,
        "apparentTemperatureHigh": -17.87,
        "apparentTemperatureHighTime": 1674900000,
        "apparentTemperatureLow": -18.92,
        "apparentTemperatureLowTime": 1674694800,
        "dewPoint": -11.37,
        "humidity": 0.87,
        "pressure": 1000.84,
        "windSpeed": 25.74,
        "windGust": 57.69,
        "windGustTime": 1674702000,
        "windBearing": 77.96,
        "cloudCover": 1.0,
        "uvIndex": 0.06,
        "uvIndexTime": 1674691200,
        "visibility": 0.68,
        "temperatureMin": -9.96,
        "temperatureMinTime": 1674694800,
        "temperatureMax": -9.21,
        "temperatureMaxTime": 1674702000,
        "apparentTemperatureMin": -18.92,
        "apparentTemperatureMinTime": 1674694800,
        "apparentTemperatureMax": -17.87,
        "apparentTemperatureMaxTime": 1674687600
```

If I convert 1674900000 into date/time format I get this: Saturday, January 28, 2023 5:00:00 AM GMT-05:00 which isn't even remotely close to the current day.

I don't know if it's possible before updating high/low/min/max to compare the previous value to the upcoming ones for the current day and only update them if they are higher/lower? Would solve the issue of needing to look at previous files if it's possible.

**Comment by cloneofghosts** [comment] 2023-01-31 16:29
@alexander0042 It looks like the high/low temperatures are being calculated from 4am-4am instead of the stated 6am-6am. Looking at the daily block it shows a low temperature time of Wednesday, February 1, 2023 4:00:00 AM GMT-05:00

But looking through the hourly blocks I see that at Wednesday, February 1, 2023 5:00:00 AM GMT-05:00 there is a lower temperature than what the daily block shows. I have the daily block and the hourly block from the API shown below with just the relevant information.

Daily:
```
        "time": 1675141200,
        "temperatureHigh": -8.96,
        "temperatureHighTime": 1675195200,
        "temperatureLow": -26.65,
        "temperatureLowTime": 1675242000,
      },
```
Hourly:
```
      {
        "time": 1675245600,
        "temperature": -27.21,
      },
```

**Comment by alexander0042** [comment] 2023-01-31 18:18
I totally understand why Dark Sky decided to depreciate the TemperatureHigh/ TemperatureLow parameters now, they're not at all intuitive, and really are a pain to work with. This is a good catch though, since this is a bug. TemperatureLow should be from 6 pm to 6 am, so the fact that it's not picking up the 5 am value is an issue. I'm 90% sure it's an "off by one" problem, so that's where I'll start. 

More broadly here, I was thinking about what @rosenbergj's comment a lot, and I really don't like the answer I came up with. It really isn't too tricky for me to get the values for earlier in the current day. I realized that since this is only for temperature, that's the only value I'd need to read, so honestly pretty doable. I'm going to try to implement this over the weekend and see how it goes,

**Comment by cloneofghosts** [comment] 2023-02-04 16:39
@alexander0042 When the temperatures rise throughout the day it's possible to have a low temperature that is higher then the high temperature. There isn't anything wrong with your current setup and maybe the easiest solution would be to swap the values if the high temp is lower then the low temp or you could just leave as is? Not sure what would be the best solution for this quirk.

```
        "time": 1675486800,
        "icon": "snow",
        "summary": "Snow",
        "sunriseTime": 1675513212,
        "sunsetTime": 1675548836,
        "moonPhase": 0.46524949386685727,
        "precipIntensity": 0.0704,
        "precipIntensityMax": 0.1711,
        "precipIntensityMaxTime": 1675566000,
        "precipProbability": 0.172,
        "precipAccumulation": 0.8453,
        "precipType": "snow",
        "temperatureHigh": -16.27,
        "temperatureHighTime": 1675544400,
        "temperatureLow": -14.59,
        "temperatureLowTime": 1675551600,
        "apparentTemperatureHigh": -18.03,
        "apparentTemperatureHighTime": 1675544400,
        "apparentTemperatureLow": -34.86,
        "apparentTemperatureLowTime": 1675558800,
        "dewPoint": -20.62,
        "humidity": 0.747,
        "pressure": 1016.4,
        "windSpeed": 12.36,
        "windGust": 26.49,
        "windGustTime": 1675537200,
        "windBearing": 166.95,
        "cloudCover": 0.991,
        "uvIndex": 2.57,
        "uvIndexTime": 1675533600,
        "visibility": 16.09,
        "temperatureMin": -25.52,
        "temperatureMinTime": 1675526400,
        "temperatureMax": -13.27,
        "temperatureMaxTime": 1675566000,
        "apparentTemperatureMin": -34.86,
        "apparentTemperatureMinTime": 1675526400,
        "apparentTemperatureMax": -18.03,
        "apparentTemperatureMaxTime": 1675566000
```

I think the same "off by one" issue exists for the high temperature since it's showing a high time of 4pm today instead of 5pm.

**Comment by rosenbergj** [comment] 2023-02-06 17:18
> When the temperatures rise throughout the day it's possible to have a low temperature that is higher then the high temperature.

I think it should be left as-is. The high and low represent different non-overlapping time periods, so it's consistent that this might happen sometimes. The code using the API can take this into account by loooking at Max and Min, for example.

**Comment by cloneofghosts** [comment] 2023-02-07 18:10
I understand that from the way its been setup high/low temperatures are for different time ranges and you can always look at min/max temperatures if needed.

I checked around on other websites to see how they handle this situation and most seem to try and have a high temperature that is higher then the low temperature outside of Environment Canada where it showed a low temperature higher then the high temperature. It doesn't bother me either way but I posted about it in case others have a preference one way or the other.

**Comment by Monstergerm** [comment] 2023-04-17 22:24
I think there is another issue with the forecasted daily0 temperatureHigh.

I expect this to be a forecast of the expected temperature High for today that stays the same during the forecast period (today or 4 am to 4 am whatever it is). Perhaps it is acceptable to increase the value of forecasted temperature if during the day the actual temperature increases above this value.

However, what I found is that the daily0 temperatureHigh constantly changes throughout the day and in particular in the afternoon seems to track the current temperature and will get lower and lower. In other words, if the forecast value for daily0 temperatureHigh was 65 F and this value was reached at 1 pm, I now notice during the afternoon daily0 temperatureHigh values of e.g. 60 F at 4 pm, which is the exact current temperature at 4 pm. I expect daily0 temperatureHigh to stay fixed at 65 F until the next forecast period starts. It should not be the temperature High from the current time until end of forecast period.

**Comment by cloneofghosts** [comment] 2024-03-12 14:26
This issue has been fixed in the V2 development API which you can access using the dev endpoint.

**Closed by cloneofghosts** 2024-03-12 14:26 UTC
Labels: bug, keep

**Comment by alexander0042** [comment] 2024-03-12 14:30
Filed under "it seemed so much easier than it was", but 2 years later we're here. The overriding issue was that the API always took the most recent model results as the starting point; however. to do this correctly you need to know what happened over the previous (up to) 24 hours, so the data just wasn't there. Complicating things was that I didn't want to use forecast results for times that had already happened, which reduces accuracy, and minimize read calls, since that slows it down. Version 2 fixes all this by reading in the previous 36 hours of observations when making a new forecast file, which gives the API access to that data directly!
