### ISSUE TITLE
Nearest Storm Not Working

### ISSUE THREAD

**Issue by dmccabe79** [Pirate-Weather/pirateweather#6] opened 2022-07-09 15:43 UTC
I've been sitting through a few days of stormy weather and the "nearest storm" function has remained at zero. Have you seen this before or maybe I have this setup incorrectly.

**Comment by dmccabe79** [comment] 2022-07-13 19:16
I've experimented with calculating a median distance and azimuth from Blitzortung lightning strikes. It's rough because of having errant strikes here and there, but paints a broad picture as to where the majority of the convective activity is. I should really keep working on that.

**Comment by alexander0042** [comment] 2022-07-14 02:01
Lightning is an interesting idea! This is why I love open source projects, since there are so many great ideas and solutions to these sorts of difficult problems. 

I hadn't seen that website before, so I'll take a deeper dive into it. It looks like they have the data archived somehow, which would be step 1 to getting it into the API. It's amazing that it has global coverage, since that's always a concern with weather data sources.

**Comment by AD-Wright** [comment] 2023-07-12 00:18
What meanest thou, Bot?  Forsooth, the last activity was 5 days ago!

**Comment by cloneofghosts** [comment] 2023-07-12 00:55
Referencing an issue from a different issue doesn't count as activity on this issue. I think activity is defined as changing the label, changing who the issue is assigned to, editing a comment, editing the title or adding/removing a comment.

**Comment by alexander0042** [comment] 2023-07-13 18:04
This + text summaries are the two things that Dark Sky did that Pirate Weather doesn't, and so I've tagged this as "keep" so it stays open. Seems unrelated, but this one will actually be fixed in conjunction with the "daily max/ min" change.  

After mulling it over, I think precipitation rate is probably the best way forward. Lightning would be cool, but won't work for winter storms, and there's no good/ easily accessible database. So the game plan is:

1. Mask off all cells with a precipitation intensity > x mm/h (I'm thinking 2 mm/h), probably using the GEFS results (lower res/ global, so easier to process, and better precipitation).
2. Run the xarray [proximity distance function](https://xarray-spatial.org/user_guide/proximity.html#Proximity-Distance), which will give me a distance and a direction for every point on the grid.
3. Loop over every time step.

**Comment by cloneofghosts** [comment] 2023-07-28 19:39
> After mulling it over, I think precipitation rate is probably the best way forward. Lightning would be cool, but won't work for winter storms, and there's no good/ easily accessible database.

There was a comment earlier in this issue about potentially using Blitzortung lightning data to figure out where storms are. I assume you've looked into it and found that it can't easily be added to the API? If it were to be added you could use a combination of lightning strikes and precipitation rate to figure out where a storm is.

Plus during the summer storms can pop up pretty quickly and since you're using GEFS data it could miss some summer storms because it only updates every 6h.

**Comment by alexander0042** [comment] 2023-07-31 14:44
Good points @cloneofghosts. The way it's shaping up is using the 15 minute HRRR data for this, which should capture summer storms in southern Canada/ US at least. It'll be GFS elsewhere (since that at least gives me hourly), but since it doesn't need to match precipitation probability, I don't need to fall back to GEFS

**Comment by cloneofghosts** [comment] 2024-02-20 22:57
This issue has been fixed on the V2 development API which should be out some time this winter.

**Closed by cloneofghosts** 2024-02-20 22:57 UTC
Labels: enhancement, keep

**Comment by alexander0042** [comment] 2024-02-22 00:31
Thanks for cleaning this up- I'm pretty excited for this feature to launch!
