### ISSUE TITLE
API occasionally returns "Artic Cold" -460 degrees

### ISSUE THREAD

**Issue by Leftium** [Pirate-Weather/pirateweather#255] opened 2024-06-24 01:43 UTC
### Describe the issue

![image](https://github.com/Pirate-Weather/pirateweather/assets/381217/16cd35c5-2c24-4205-b75b-2bc20e71df2c)

This is the second time I have seen "Arctic Cold." Last time, nearly the entire last day was "Arctic Cold."

<details>
<summary><b>(Abbreviated) JSON data</b></summary>
<pre>
{
  "latitude": 37.6155683,
  "longitude": 126.7157798,
  "timezone": "Asia/Seoul",
  "offset": 9,
  "elevation": 34,
  "currently": {
    "time": 1719154800,
    "summary": "Rain",
    "icon": "rain",
    "nearestStormDistance": 22.08,
    "nearestStormBearing": 90,
    "precipIntensity": 1.3375,
    "precipProbability": 1,
    "precipIntensityError": 0.68,
    "precipType": "rain",
    "temperature": 22.64,
    "apparentTemperature": 22.67,
    "dewPoint": 20.85,
    "humidity": 0.89,
    "pressure": 995.79,
    "windSpeed": 3.35,
    "windGust": 5.01,
    "windBearing": 209,
    "cloudCover": 0.46,
    "uvIndex": 0,
    "visibility": 14.7,
    "ozone": 344.31
  },
  "minutely": {
    "summary": "Rain",
    "icon": "rain",
    "data": [
      {
        "time": 1719154800,
        "precipIntensity": 1.3375,
        "precipProbability": 1,
        "precipIntensityError": 0.68,
        "precipType": "rain"
      },
      {
        "time": 1719154860,
        "precipIntensity": 1.3357,
        "precipProbability": 1,
        "precipIntensityError": 0.67,
        "precipType": "rain"
      },
      {
        "time": 1719154920,
        "precipIntensity": 1.3328,
        "precipProbability": 1,
        "precipIntensityError": 0.67,
        "precipType": "rain"
      },
      {
        "time": 1719154980,
        "precipIntensity": 1.3298,
        "precipProbability": 1,
        "precipIntensityError": 0.67,
        "precipType": "rain"
      },
      {
        "time": 1719155040,
        "precipIntensity": 1.3269,
        "precipProbability": 1,
        "precipIntensityError": 0.67,
        "precipType": "rain"
      },
      {
        "time": 1719155100,
        "precipIntensity": 1.3239,
        "precipProbability": 1,
        "precipIntensityError": 0.67,
        "precipType": "rain"
      },
      {
        "time": 1719155160,
        "precipIntensity": 1.321,
        "precipProbability": 1,
        "precipIntensityError": 0.67,
        "precipType": "rain"
      },
      {
        "time": 1719155220,
        "precipIntensity": 1.318,
        "precipProbability": 1,
        "precipIntensityError": 0.67,
        "precipType": "rain"
      },
      {
        "time": 1719155280,
        "precipIntensity": 1.3151,
        "precipProbability": 1,
        "precipIntensityError": 0.67,
        "precipType": "rain"
      },
      {
        "time": 1719155340,
        "precipIntensity": 1.3121,
        "precipProbability": 1,
        "precipIntensityError": 0.67,
        "precipType": "rain"
      },
      {
        "time": 1719155400,
        "precipIntensity": 1.3092,
        "precipProbability": 1,
        "precipIntensityError": 0.66,
        "precipType": "rain"
      },
      {
        "time": 1719155460,
        "precipIntensity": 1.3062,
        "precipProbability": 1,
        "precipIntensityError": 0.66,
        "precipType": "rain"
      },
      {
        "time": 1719155520,
        "precipIntensity": 1.3033,
        "precipProbability": 1,
        "precipIntensityError": 0.66,
        "precipType": "rain"
      },
      {
        "time": 1719155580,
        "precipIntensity": 1.3003,
        "precipProbability": 1,
        "precipIntensityError": 0.66,
        "precipType": "rain"
      },
      {
        "time": 1719155640,
        "precipIntensity": 1.2974,
        "precipProbability": 1,
        "precipIntensityError": 0.66,
        "precipType": "rain"
      },
      {
        "time": 1719155700,
        "precipIntensity": 1.2945,
        "precipProbability": 1,
        "precipIntensityError": 0.66,
        "precipType": "rain"
      },
      {
        "time": 1719155760,
        "precipIntensity": 1.2915,
        "precipProbability": 1,
        "precipIntensityError": 0.66,
        "precipType": "rain"
      },
      {
        "time": 1719155820,
        "precipIntensity": 1.2886,
        "precipProbability": 1,
        "precipIntensityError": 0.66,
        "precipType": "rain"
      },
      {
        "time": 1719155880,
        "precipIntensity": 1.2856,
        "precipProbability": 1,
        "precipIntensityError": 0.65,
        "precipType": "rain"
      },
      {
        "time": 1719155940,
        "precipIntensity": 1.2827,
        "precipProbability": 1,
        "precipIntensityError": 0.65,
        "precipType": "rain"
      },
      {
        "time": 1719156000,
        "precipIntensity": 1.2797,
        "precipProbability": 1,
        "precipIntensityError": 0.65,
        "precipType": "rain"
      },
      {
        "time": 1719156060,
        "precipIntensity": 1.2768,
        "precipProbability": 1,
        "precipIntensityError": 0.65,
        "precipType": "rain"
      },
      {
        "time": 1719156120,
        "precipIntensity": 1.2738,
        "precipProbability": 1,
        "precipIntensityError": 0.65,
        "precipType": "rain"
      },
      {
        "time": 1719156180,
        "precipIntensity": 1.2709,
        "precipProbability": 1,
        "precipIntensityError": 0.65,
        "precipType": "rain"
      },
      {
        "time": 1719156240,
        "precipIntensity": 1.2679,
        "precipProbability": 1,
        "precipIntensityError": 0.65,
        "precipType": "rain"
      },
      {
        "time": 1719156300,
        "precipIntensity": 1.265,
        "precipProbability": 1,
        "precipIntensityError": 0.65,
        "precipType": "rain"
      },
      {
        "time": 1719156360,
        "precipIntensity": 1.262,
        "precipProbability": 1,
        "precipIntensityError": 0.65,
        "precipType": "rain"
      },
      {
        "time": 1719156420,
        "precipIntensity": 1.2591,
        "precipProbability": 1,
        "precipIntensityError": 0.64,
        "precipType": "rain"
      },
      {
        "time": 1719156480,
        "precipIntensity": 1.2561,
        "precipProbability": 1,
        "precipIntensityError": 0.64,
        "precipType": "rain"
      },
      {
        "time": 1719156540,
        "precipIntensity": 1.2532,
        "precipProbability": 1,
        "precipIntensityError": 0.64,
        "precipType": "rain"
      },
      {
        "time": 1719156600,
        "precipIntensity": 1.2502,
        "precipProbability": 1,
        "precipIntensityError": 0.64,
        "precipType": "rain"
      },
      {
        "time": 1719156660,
        "precipIntensity": 1.2473,
        "precipProbability": 1,
        "precipIntensityError": 0.64,
        "precipType": "rain"
      },
      {
        "time": 1719156720,
        "precipIntensity": 1.2443,
        "precipProbability": 1,
        "precipIntensityError": 0.64,
        "precipType": "rain"
      },
      {
        "time": 1719156780,
        "precipIntensity": 1.2414,
        "precipProbability": 1,
        "precipIntensityError": 0.64,
        "precipType": "rain"
      },
      {
        "time": 1719156840,
        "precipIntensity": 1.2384,
        "precipProbability": 1,
        "precipIntensityError": 0.64,
        "precipType": "rain"
      },
      {
        "time": 1719156900,
        "precipIntensity": 1.2355,
        "precipProbability": 1,
        "precipIntensityError": 0.64,
        "precipType": "rain"
      },
      {
        "time": 1719156960,
        "precipIntensity": 1.2325,
        "precipProbability": 1,
        "precipIntensityError": 0.63,
        "precipType": "rain"
      },
      {
        "time": 1719157020,
        "precipIntensity": 1.2296,
        "precipProbability": 1,
        "precipIntensityError": 0.63,
        "precipType": "rain"
      },
      {
        "time": 1719157080,
        "precipIntensity": 1.2266,
        "precipProbability": 1,
        "precipIntensityError": 0.63,
        "precipType": "rain"
      },
      {
        "time": 1719157140,
        "precipIntensity": 1.2237,
        "precipProbability": 1,
        "precipIntensityError": 0.63,
        "precipType": "rain"
      },
      {
        "time": 1719157200,
        "precipIntensity": 1.2207,
        "precipProbability": 1,
        "precipIntensityError": 0.63,
        "precipType": "rain"
      },
      {
        "time": 1719157260,
        "precipIntensity": 1.2178,
        "precipProbability": 1,
        "precipIntensityError": 0.63,
        "precipType": "rain"
      },
      {
        "time": 1719157320,
        "precipIntensity": 1.2148,
        "precipProbability": 1,
        "precipIntensityError": 0.63,
        "precipType": "rain"
      },
      {
        "time": 1719157380,
        "precipIntensity": 1.2119,
        "precipProbability": 1,
        "precipIntensityError": 0.63,
        "precipType": "rain"
      },
      {
        "time": 1719157440,
        "precipIntensity": 1.209,
        "precipProbability": 1,
        "precipIntensityError": 0.62,
        "precipType": "rain"
      },
      {
        "time": 1719157500,
        "precipIntensity": 1.206,
        "precipProbability": 1,
        "precipIntensityError": 0.62,
        "precipType": "rain"
      },
      {
        "time": 1719157560,
        "precipIntensity": 1.2031,
        "precipProbability": 1,
        "precipIntensityError": 0.62,
        "precipType": "rain"
      },
      {
        "time": 1719157620,
        "precipIntensity": 1.2001,
        "precipProbability": 1,
        "precipIntensityError": 0.62,
        "precipType": "rain"
      },
      {
        "time": 1719157680,
        "precipIntensity": 1.1972,
        "precipProbability": 1,
        "precipIntensityError": 0.62,
        "precipType": "rain"
      },
      {
        "time": 1719157740,
        "precipIntensity": 1.1942,
        "precipProbability": 1,
        "precipIntensityError": 0.62,
        "precipType": "rain"
      },
      {
        "time": 1719157800,
        "precipIntensity": 1.1913,
        "precipProbability": 1,
        "precipIntensityError": 0.62,
        "precipType": "rain"
      },
      {
        "time": 1719157860,
        "precipIntensity": 1.1883,
        "precipProbability": 1,
        "precipIntensityError": 0.62,
        "precipType": "rain"
      },
      {
        "time": 1719157920,
        "precipIntensity": 1.1854,
        "precipProbability": 1,
        "precipIntensityError": 0.62,
        "precipType": "rain"
      },
      {
        "time": 1719157980,
        "precipIntensity": 1.1824,
        "precipProbability": 1,
        "precipIntensityError": 0.61,
        "precipType": "rain"
      },
      {
        "time": 1719158040,
        "precipIntensity": 1.1795,
        "precipProbability": 1,
        "precipIntensityError": 0.61,
        "precipType": "rain"
      },
      {
        "time": 1719158100,
        "precipIntensity": 1.1765,
        "precipProbability": 1,
        "precipIntensityError": 0.61,
        "precipType": "rain"
      },
      {
        "time": 1719158160,
        "precipIntensity": 1.1736,
        "precipProbability": 1,
        "precipIntensityError": 0.61,
        "precipType": "rain"
      },
      {
        "time": 1719158220,
        "precipIntensity": 1.1706,
        "precipProbability": 1,
        "precipIntensityError": 0.61,
        "precipType": "rain"
      },
      {
        "time": 1719158280,
        "precipIntensity": 1.1677,
        "precipProbability": 1,
        "precipIntensityError": 0.61,
        "precipType": "rain"
      },
      {
        "time": 1719158340,
        "precipIntensity": 1.1647,
        "precipProbability": 1,
        "precipIntensityError": 0.61,
        "precipType": "rain"
      },
      {
        "time": 1719158400,
        "precipIntensity": 1.1618,
        "precipProbability": 1,
        "precipIntensityError": 0.61,
        "precipType": "rain"
      }
    ]
  },
  "hourly": {
    "summary": "Cloudy",
    "icon": "cloudy",
    "data": [
      {
        "time": 1719154800,
        "icon": "rain",
        "summary": "Rain",
        "precipIntensity": 1.3379,
        "precipProbability": 1,
        "precipIntensityError": 1.3379,
        "precipAccumulation": 0.1338,
        "precipType": "rain",
        "temperature": 22.64,
        "apparentTemperature": 22.67,
        "dewPoint": 20.85,
        "humidity": 0.9,
        "pressure": 995.79,
        "windSpeed": 3.35,
        "windGust": 5.01,
        "windBearing": 208.68,
        "cloudCover": 0.46,
        "uvIndex": 0,
        "visibility": 14.7,
        "ozone": 344.31
      },
      {
        "time": 1719158400,
        "icon": "rain",
        "summary": "Rain",
        "precipIntensity": 1.1618,
        "precipProbability": 1,
        "precipIntensityError": 1.1618,
        "precipAccumulation": 0.1162,
        "precipType": "rain",
        "temperature": 21.78,
        "apparentTemperature": 21.85,
        "dewPoint": 20.55,
        "humidity": 0.93,
        "pressure": 995.52,
        "windSpeed": 4.1,
        "windGust": 6.8,
        "windBearing": 211.43,
        "cloudCover": 0.41,
        "uvIndex": 0,
        "visibility": 9.42,
        "ozone": 342.92
      },
...
...
      {
        "time": 1719586800,
        "icon": "rain",
        "summary": "Rain",
        "sunriseTime": 1719605687,
        "sunsetTime": 1719658705,
        "moonPhase": 0.77,
        "precipIntensity": 0.1111,
        "precipIntensityMax": 0.4502,
        "precipIntensityMaxTime": 1719586800,
        "precipProbability": 0.13,
        "precipAccumulation": 0.2071,
        "precipType": "rain",
        "temperatureHigh": 28.94,
        "temperatureHighTime": 1719633600,
        "temperatureLow": 23.77,
        "temperatureLowTime": 1719691200,
        "apparentTemperatureHigh": 30.78,
        "apparentTemperatureHighTime": 1719633600,
        "apparentTemperatureLow": 22.6,
        "apparentTemperatureLowTime": 1719604800,
        "dewPoint": 20.78,
        "humidity": 0.76,
        "pressure": 1005.9,
        "windSpeed": 4.31,
        "windGust": 7.27,
        "windGustTime": 1719644400,
        "windBearing": 187.46,
        "cloudCover": 0.73,
        "uvIndex": 7.25,
        "uvIndexTime": 1719637200,
        "visibility": 16.09,
        "temperatureMin": 22.54,
        "temperatureMinTime": 1719604800,
        "temperatureMax": 28.94,
        "temperatureMaxTime": 1719633600,
        "apparentTemperatureMin": 22.54,
        "apparentTemperatureMinTime": 1719604800,
        "apparentTemperatureMax": 30.78,
        "apparentTemperatureMaxTime": 1719633600
      },
      {
        "time": 1719673200,
        "icon": "rain",
        "summary": "Rain",
        "sunriseTime": 1719692112,
        "sunsetTime": 1719745102,
        "moonPhase": 0.81,
        "precipIntensity": 0.8487,
        "precipIntensityMax": 1.2758,
        "precipIntensityMaxTime": 1719673200,
        "precipProbability": 0.4,
        "precipAccumulation": 2.0368,
        "precipType": "rain",
        "temperatureHigh": 27.91,
        "temperatureHighTime": 1719712800,
        "temperatureLow": -273.15,
        "temperatureLowTime": 1719752400,
        "apparentTemperatureHigh": 29.07,
        "apparentTemperatureHighTime": 1719716400,
        "apparentTemperatureLow": -273.15,
        "apparentTemperatureLowTime": 1719752400,
        "dewPoint": -4.37,
        "humidity": 0.65,
        "pressure": 920.23,
        "windSpeed": 4.59,
        "windGust": 10.29,
        "windGustTime": 1719738000,
        "windBearing": 183.5,
        "cloudCover": 0.88,
        "uvIndex": 3.74,
        "uvIndexTime": 1719716400,
        "visibility": 14.75,
        "temperatureMin": -273.15,
        "temperatureMinTime": 1719752400,
        "temperatureMax": 27.91,
        "temperatureMaxTime": 1719712800,
        "apparentTemperatureMin": -273.15,
        "apparentTemperatureMinTime": 1719752400,
        "apparentTemperatureMax": 29.07,
        "apparentTemperatureMaxTime": 1719716400
      },
      {
        "time": 1719759600,
        "icon": "rain",
        "summary": "Rain",
        "sunriseTime": 1719778539,
        "sunsetTime": 1719831497,
        "moonPhase": 0.84,
        "precipIntensity": 0.3422,
        "precipIntensityMax": 1.0361,
        "precipIntensityMaxTime": 1719759600,
        "precipProbability": 0.37,
        "precipAccumulation": 0.8212,
        "precipType": "rain",
        "temperatureHigh": -273.15,
        "temperatureHighTime": 1719781200,
        "temperatureLow": -273.15,
        "temperatureLowTime": 1719824400,
        "apparentTemperatureHigh": -273.15,
        "apparentTemperatureHighTime": 1719759600,
        "apparentTemperatureLow": -273.15,
        "apparentTemperatureLowTime": 1719759600,
        "dewPoint": -273.15,
        "humidity": 0,
        "pressure": 0,
        "windSpeed": 0,
        "windGust": 0,
        "windGustTime": 1719759600,
        "windBearing": 180,
        "cloudCover": 0,
        "uvIndex": 0,
        "uvIndexTime": 1719759600,
        "visibility": 0,
        "temperatureMin": -273.15,
        "temperatureMinTime": 1719759600,
        "temperatureMax": -273.15,
        "temperatureMaxTime": 1719759600,
        "apparentTemperatureMin": -273.15,
        "apparentTemperatureMinTime": 1719759600,
        "apparentTemperatureMax": -273.15,
        "apparentTemperatureMaxTime": 1719759600
      }
    ]
  },
  "flags": {
    "sources": [
      "ETOPO1",
      "gfs",
      "gefs"
    ],
    "sourceTimes": {
      "gfs": "2024-06-20 12Z",
      "gefs": "2024-06-23 12Z"
    },
    "nearest-station": 0,
    "units": "si",
    "version": "V2.0.10"
  },
  "time": 1719154800,
  "merry": {
    "timezone": "Asia/Seoul",
    "location": {
      "center": [
        126.7157798,
        37.6155683
      ],
      "name": "김포시, 경기도, 대한민국",
      "bbox": [
        126.5151715,
        37.579557,
        126.8025933,
        37.7920214
      ]
    },
    "country": "KOR",
    "source": "pirateweather"
  }
}

</pre>

</details>

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment] 2024-06-24 14:34
Duplicate of https://github.com/Pirate-Weather/pirateweather/issues/229

This issue should hopefully be fixed shortly.

**Closed by cloneofghosts** 2024-06-24 14:34 UTC
Labels: duplicate
