### ISSUE TITLE
Extreme spikes / outliers in temperature

### ISSUE THREAD

**Issue by SaturnusDJ** [Pirate-Weather/pirateweather#289] opened 2024-08-12 14:17 UTC
Did I post in the wrong repo?
https://github.com/Pirate-Weather/pirateweather/issues/283 Related?
Let me know.

### Describe the bug

![image](https://github.com/user-attachments/assets/84620783-4181-4a43-8a48-9ef1827a9656)

This happens every few weeks. A lot more recently though.

### Expected behavior

I don't know what the data source is and how this is processed, but can this be filtered out? A filter in pirate weather that drops these extreme values?

### Actual behavior

These extreme values seem to happen mostly around midnight.

They immediately disturb the graph view in HA as shown above. Any detail is lost by this hit of 600 degrees C. And of course, automations related to opening/closing windows, enabling heating/cooling, based on the temperature outside are failing.

### Home Assistant version

2024.6.4

### Integration version

1.5.3

### Other details

Yes, sorry, I am on an 'old' version of HA. I cannot afford down time, bugs or issues in the household and therefore lack behind in version. (See for example big issues in the 7 release of this year. https://community.home-assistant.io/t/2024-7-time-to-resize-your-cards/745771.)

The report about the issue I am making here has been happening for months. There should not be a relationship with the HA version. I did check the release notes of 2024.7 and 2024.8 and have not found anything that could be related to this issue.

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment] 2024-08-12 15:20
Thanks for the report. I've moved this issue over to the API repository as the issue is with the API and has nothing to do with the HA integration. Yes, the issue you linked and #284 are related to your issues which should be fixed once @alexander0042 releases V2.1 of the API. I don't have an ETA on when it will be released but I would think it should be soon.

**Comment by SaturnusDJ** [comment] 2024-08-14 20:25
Thanks. 👌🏼 Will keep an eye on it.

**Closed** 2024-08-15 13:28 UTC
Labels: bug, priority: urgent
