### ISSUE TITLE
Very high & low temperature values

### ISSUE THREAD

**Issue by brott8** [Pirate-Weather/pirateweather#230] opened 2024-05-18 14:41 UTC
### Describe the bug

For Melbourne, Victoria, I am getting bizarre highs and lows. Through merry sky, I see a high of 999900026055400900000° today and a low of -273. Similarly odd values for tomorrow's temperature ranges. 

### Expected behavior

Today should be around a high of 16 and a low of 6. 

### Actual behavior

Highs and lows well beyond those seen on Mercury. 

### API Endpoint

Production

### Location

Melbourne, Victoria, Australia 

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment] 2024-05-18 16:12
Duplicate of #229

**Closed** 2024-05-18 16:12 UTC
Labels: bug, duplicate
